"""initial schema

Revision ID: c1a7c5cca2c1
Revises: 
Create Date: 2026-04-20 13:04:31.259766

"""
from alembic import op
import sqlalchemy as sa


revision = 'c1a7c5cca2c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
